### ISSUE TITLE
netcdf.h was not compiled on mac OS

### ISSUE THREAD

**Issue by Shideler** [DanielQuiroz97/RGCxGC#1]
I have been trying to install RGCxGC all day. I have tried two methods for this. 

1. CRAN installer in Rstudio

2. > library(devtools)
> install_github("DanielQuiroz97/RGCxGC")

I have a MacBook Pro 2019 - With macOS Catalina 

I get the following error: 

Downloading GitHub repo DanielQuiroz97/RGCxGC@master
Skipping 1 packages ahead of CRAN: mixOmics
Installing 2 packages: RNetCDF, BH
Installing packages into ‘/Users/steve/Library/R/3.6/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/RNetCDF_2.1-1.tar.gz'
Content type 'application/x-gzip' length 118055 bytes (115 KB)
==================================================
downloaded 115 KB

trying URL 'https://cran.rstudio.com/src/contrib/BH_1.72.0-3.tar.gz'
Content type 'application/x-gzip' length 11850400 bytes (11.3 MB)
==================================================
downloaded 11.3 MB

* installing *source* package ‘RNetCDF’ ...
** package ‘RNetCDF’ successfully unpacked and MD5 sums checked
** using staged installation
checking for nc-config... no
checking for gcc... x86_64-apple-darwin13.4.0-clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-apple-darwin13.4.0-clang accepts -g... yes
checking for x86_64-apple-darwin13.4.0-clang option to accept ISO C89... none needed
checking how to run the C preprocessor... x86_64-apple-darwin13.4.0-clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking netcdf.h usability... no
checking netcdf.h presence... no
checking for netcdf.h... no
configure: error: netcdf.h was not compiled - defining CPPFLAGS may help
ERROR: configuration failed for package ‘RNetCDF’
* removing ‘/Users/steve/Library/R/3.6/library/RNetCDF’
Error: Failed to install 'RGCxGC' from GitHub:
  (converted from warning) installation of package ‘RNetCDF’ had non-zero exit status

Initially, ptw mixOmics and a few other dependencies were not loading either, but I was able to install each of those missing dependencies one by one. 

I am still stuck on the RNetCDF, there is a problem with the nc-config, but the file doesn't exist at all on my machine and despite hours of effort, I cannot find a work around for this. 

I would really like to use this package you have created. Do you have any tips that might help?

**Comment by DanielQuiroz97** [comment]
Really sorry for the delay,

I had some health issues last weeks.

I found that the same error is persistent with mac based OS. Please refer to this issue. 

https://github.com/mjwoods/RNetCDF/issues/48#issuecomment-464299706

Let me know if it was fixed or have some errors. BTW, you can find me at this .
