### ISSUE TITLE
Tutorial/PDF no longer available

### ISSUE THREAD

**Issue by MikeDereviankin** [DanielQuiroz97/RGCxGC#3]
As this package has been archived, there is no available PDF documentation and/or tutorial on how to use for training purposes. 

Would you be able to re-upload these documents?

**Comment by DanielQuiroz97** [comment]
Dear @MikeDereviankin,

As of today, Dec 13, the pkgdown site is up and you can take a look at the tutorials precompiled in this website.

https://danielquiroz97.github.io/RGCxGC/

Do not hesitate to report any bugs,
Best regards,
Daniel
